videos:
  - "video_1"
  - "video_2"
  - "video_3"
  - "video_4"
  - "video_5"
  - "video_6"
#  - "video_7"
#  - "video_8"
#  - "video_9"
#  - "video_10"
strategies:
  - "ProCES-360"
  - "BASELINE"
  - "EPRO"
  - "MFQAS"
  - "AC-KKT"
  - "TPMOA"